version: "2"

linters:
  enable:
    - goconst
    - misspell
    - prealloc
    - predeclared
    - revive
    - testpackage
    - unconvert
    - unparam
    - whitespace
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true

